/* Generated By:JavaCC: Do not edit this line. calConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface calConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LEFT_PAREN = 5;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 6;
  /** RegularExpression Id. */
  int INCREMENT = 7;
  /** RegularExpression Id. */
  int DECREMENT = 8;
  /** RegularExpression Id. */
  int LEFT_BRACE = 9;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 10;
  /** RegularExpression Id. */
  int SEMICOLON = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int X = 13;
  /** RegularExpression Id. */
  int Y = 14;
  /** RegularExpression Id. */
  int ASIGNMENT = 15;
  /** RegularExpression Id. */
  int IDENTIFIER = 16;
  /** RegularExpression Id. */
  int INT_NUMBER = 17;
  /** RegularExpression Id. */
  int FLOAT_NUMBER = 18;
  /** RegularExpression Id. */
  int ERROR = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"(\"",
    "\")\"",
    "\"++\"",
    "\"--\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"X\"",
    "\"Y\"",
    "\"= \"",
    "<IDENTIFIER>",
    "<INT_NUMBER>",
    "<FLOAT_NUMBER>",
    "<ERROR>",
  };

}
